### ISSUE TITLE
Pubkey Divide

### ISSUE THREAD

**Issue by makabress** [iceland2k14/quick#2]
hi
thank you for this tool

just a question about divide

i trayed a 5 bit dividor i can confirm that the first pubkey result is divided by 32 , but i can't find the dividor of the other result

**Comment by iceland2k14** [comment]
Yes Correct. 1 of them will be in reduced range.
All Others will go closer to the Order//2 or Order of the Curve.

**Comment by makabress** [comment]
Ok thank you for explanation

But i think an incremental dividor is better and will give result

**Comment by iceland2k14** [comment]
That's correct.
It's already incremental  --> https://github.com/iceland2k14/quick/blob/e4312eac3e944004549bf9d97657f2e0b8199de5/PubDiv.py#L58-L60
