### ISSUE TITLE
small_subgroup_ETH.py

### ISSUE THREAD

**Issue by djmuratb** [iceland2k14/quick#6]
Hi,
After a while I run out of free space on my SSD and it says the following error:

---------------------------------------------
Traceback (most recent call last):
  File "C:\Workshop\python\iceland2k14\quick\small_subgroup_ETH.py", line 78, in <module>
    addr4 = privatekey_to_ETH_address(np)
  File "C:\Workshop\python\iceland2k14\quick\small_subgroup_ETH.py", line 42, in privatekey_to_ETH_address
    res = ice.privatekey_to_ETH_address(pass_int_value)
OSError: exception: access violation writing 0x0000000000000018

C:\Workshop\python\iceland2k14\quick>

---------------------------------------------

Also thank you for all your work.

**Comment by iceland2k14** [comment]
Sorry, was it a disk space temporary issue or anything in the code causing to fill RAM or Disk ?

**Comment by djmuratb** [comment]
> Sorry, was it a disk space temporary issue or anything in the code causing to fill RAM or Disk ?

Hi,
I do not know exactly. It happens like this;

After a while, the SSD space gets full. (not RAM!)
There is no problem with the Bitcoin version. Only the (this) version with ETH has a problem. The codes look the same but ETH is causing problems.

Thank you for your interest.

**Comment by djmuratb** [comment]
> Sorry, was it a disk space temporary issue or anything in the code causing to fill RAM or Disk ?

I forgot to write;

When Windows is restarted, the SSD space comes back again.

**Comment by iceland2k14** [comment]
@djmuratb I have made a new repo [https://github.com/iceland2k14/secp256k1](https://github.com/iceland2k14/secp256k1) with simplified usage and some bug correction, there could be a pointer memory leak.
You might try that in case.
