### ISSUE TITLE
Pubkey divide

### ISSUE THREAD

**Issue by Elecman** [iceland2k14/quick#7]
how is it supposed to work?
for example, I took 55 bit space
seed: 41cfffe1000000
pub: 02a356773f0058ac88c31a305dd485a1dae845d1f03c790f1de5b3a08434a80cdf

`python3 PubDiv.py 02a356773f0058ac88c31a305dd485a1dae845d1f03c790f1de5b3a08434a80cdf 5 1keydiv_bit5.txt`
used to find the key:
`./keyhunt -m bsgs -f 1keydiv_bit5.txt -t 16 -b 55`

where the -b parameter is the bit space in which I'm looking ... apparently I misunderstood the principle of the code?

**Comment by iceland2k14** [comment]
No the idea is to reduce the bit space. your 55bit key after 5bit reduction will come in 50bit space. Any 1 of those reduced keys will be (100%) in 50bit and can be found by searching in the 50bit.
After that the Original 55bit key can be obtained by ....... [32*foundkey + i]    (where i is from 0 to 31)
i is equal to the index number in the file of the reduced key which you solved

**Comment by Elecman** [comment]
Спасибо, разобрался)
